#----------------------------------------
#  F77 COMPILER
#----------------------------------------
CMP77=/usr/local/mpich64/bin/mpif90 -c -vec-report0
OPT77= -O1
F77=$(CMP77)

#----------------------------------------
#  F90 COMPILER
#----------------------------------------
CMP90=/usr/local/mpich64/bin/mpif90 -c -heap-arrays 100 -vec-report0
OPT90=-r8 

#----------------------------------------
#  LINKER
#----------------------------------------
LNK=/usr/local/mpich64/bin/mpif90 -heap-arrays 100 -lpthread
LNK_OPT=

#----------------------------------------
#  C COMPILER
#----------------------------------------
CC=/usr/local/mpich64/bin/mpicc -c
COPT=-O1

#----------------------------------------
#  BUILD LIBRARY
#----------------------------------------
AR=ar rcv

#----------------------------------------
#  INCLUDE COMMANDS
#----------------------------------------
INCL_CMD=-I
LIBDIR_CMD=-L
LNKLIB_CMD=-l
